# Matrix Build Declaration
language: cpp
sudo: required
dist: trusty
branches:
  only: master
git:
  submodules: false

before_install: bash ./scripts/travis-before-install
before_script: bash ./scripts/travis-configure
install: bash ./scripts/travis-install
script: cmake --build build --target check -- CTEST_OUTPUT_ON_FAILURE=1
# We have a large number of targets to hit and travis-ci doesn't let us
# 'append' values to a given row to produce more so we need to MANUALLY
# declare all of them so that we can have "fine grained control"
matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD=Release VERSION=6
    - os: linux
      compiler: gcc
      env: BUILD=Release VERSION=5
    - os: linux
      compiler: gcc
      env: BUILD=Debug VERSION=6
    - os: linux
      compiler: gcc
      env: BUILD=Debug VERSION=5
    - os: linux
      compiler: clang
      env: BUILD=Release VERSION=3.7
#    - os: linux
#      compiler: clang
#      env: BUILD=Release VERSION=3.7 LIBCXX=ON
    - os: osx
      compiler: clang
      env: BUILD=Release
    - os: osx
      compiler: clang
      env: BUILD=Debug
