# Matrix Build Declaration
language: cpp
sudo: false
branches:
  only: master
git:
  submodules: false

before_install: bash ./scripts/travis-before-install
before_script: bash ./scripts/travis-configure
install: bash ./scripts/travis-install
script: cmake --build build --target check -- CTEST_OUTPUT_ON_FAILURE=1
after_failure:
  - cat ./build/CMakeFiles/CMakeOutput.log
  - cat ./build/CMakeFiles/CMakeError.log
# We have a large number of targets to hit and travis-ci doesn't let us
# 'append' values to a given row to produce more so we need to MANUALLY
# declare all of them so that we can have "fine grained control"
matrix:
  include:
    # osx : clang : release
    - os: osx
      compiler: clang
      env: BUILD=Release
      osx_image: xcode7.1
    - os: osx
      compiler: clang
      env: BUILD=Release
      osx_image: xcode7
    - os: osx
      compiler: clang
      env: BUILD=Release
      osx_image: xcode6.4
    - os: osx
      compiler: clang
      env: BUILD=Release
      osx_image: beta-xcode6.3
    - os: osx
      compiler: clang
      env: BUILD=Release
      osx_image: beta_xcode6.2
    - os: osx
      compiler: clang
      env: BUILD=Release
    # osx : gcc : release
    - os: osx
      compiler: gcc
      env: BUILD=Release VERSION=5
    - os: osx
      compiler: gcc
      env: BUILD=Release VERSION=4.9
    - os: osx
      compiler: gcc
      env: BUILD=Release VERSION=4.8
    # osx : clang : debug
    - os: osx
      compiler: clang
      env: BUILD=Debug
      osx_image: xcode7.1
    - os: osx
      compiler: clang
      env: BUILD=Debug
      osx_image: xcode7
    - os: osx
      compiler: clang
      env: BUILD=Debug
      osx_image: xcode6.4
    - os: osx
      compiler: clang
      env: BUILD=Debug
      osx_image: beta-xcode6.3
    - os: osx
      compiler: clang
      env: BUILD=Debug
      osx_image: beta_xcode6.2
    - os: osx
      compiler: clang
      env: BUILD=Debug
    # os x : gcc : debug
    - os: osx
      compiler: gcc
      env: BUILD=Debug VERSION=5
    - os: osx
      compiler: gcc
      env: BUILD=Debug VERSION=4.9
    - os: osx
      compiler: gcc
      env: BUILD=Debug VERSION=4.8
    # linux : clang : libc++ : release
    - os: linux
      compiler: clang
      env: BUILD=Release VERSION=3.7 LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.7
            - libc++-dev
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Release VERSION=3.6 LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - libc++-dev
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Release VERSION=3.5 LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.5
            - libc++-dev
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Release LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
          packages:
            - libc++-dev
            - cmake-data
            - cmake

    # linux : clang : libstdc++ : release
    - os: linux
      compiler: clang
      env: BUILD=Release VERSION=3.7
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Release VERSION=3.6
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Release VERSION=3.5
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Release
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8 # required to update libstdc++
            - cmake-data
            - cmake
    # linux : gcc : release
    - os: linux
      compiler: gcc
      env: BUILD=Release VERSION=5
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake-data
            - cmake
    - os: linux
      compiler: gcc
      env: BUILD=Release VERSION=4.9
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake-data
            - cmake
    - os: linux
      compiler: gcc
      env: BUILD=Release VERSION=4.8
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - cmake-data
            - cmake
    # linux : clang : libc++ : debug
    - os: linux
      compiler: clang
      env: BUILD=Debug VERSION=3.7 LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libc++-dev
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Debug VERSION=3.6 LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libc++-dev
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Debug VERSION=3.5 LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
            - libc++-dev
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Debug LIBCXX=ON
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
          packages:
            - libc++-dev
            - cmake-data
            - cmake
    # linux : clang : libstdc++ : debug
    - os: linux
      compiler: clang
      env: BUILD=Debug VERSION=3.7
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Debug VERSION=3.6
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Debug VERSION=3.5
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
            - cmake-data
            - cmake
    - os: linux
      compiler: clang
      env: BUILD=Debug
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8 # required to update libstdc++ version
            - cmake-data
            - cmake
    # linux : gcc : debug
    - os: linux
      compiler: gcc
      env: BUILD=Debug VERSION=5
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake-data
            - cmake
    - os: linux
      compiler: gcc
      env: BUILD=Debug VERSION=4.9
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake-data
            - cmake
    - os: linux
      compiler: gcc
      env: BUILD=Debug VERSION=4.8
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - cmake-data
            - cmake
